name: Cypress – H5 Playground Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:   # 👈 THIS enables "Run workflow"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install serve
        run: npm install -g serve

      - name: Start H5 Playground
        run: serve testapp -l 8080 &

      - name: Wait for app
        run: npx wait-on http://localhost:8080/eclat-shop.html

      - name: Run Cypress tests
        env:
          CYPRESS_baseUrl: http://localhost:8080
        run: npx cypress run
